# Generated by Django 5.1.5 on 2025-06-01 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_videos_uploaded_at_comment_profile_likedislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 1, 17, 12, 36, 707307)),
        ),
    ]
