# Generated by Django 5.1.5 on 2025-06-05 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_videos_viewers_alter_videos_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likedislike',
            name='is_like',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='value',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videos',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 5, 15, 5, 46, 445985)),
        ),
    ]
