# Generated by Django 5.1.5 on 2025-06-05 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_videos_uploaded_at_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 5, 19, 49, 50, 324590)),
        ),
    ]
