# Generated by Django 5.1.5 on 2025-06-07 11:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_posts_uploaded_at_alter_profile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 16, 34, 40, 934642)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 16, 34, 40, 935642)),
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.videos')),
            ],
            options={
                'ordering': ['-watched_at'],
            },
        ),
    ]
