# Generated by Django 5.2.2 on 2025-06-08 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_alter_profile_created_at_alter_videos_uploaded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 8, 9, 57, 41, 634032)
            ),
        ),
        migrations.AlterField(
            model_name="videos",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 8, 9, 57, 41, 634860)
            ),
        ),
    ]
