# Generated by Django 5.2.2 on 2025-06-08 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_profile_created_at_alter_videos_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 8, 17, 29, 10, 580786)
            ),
        ),
        migrations.AlterField(
            model_name="videos",
            name="uploaded_at",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 6, 8, 17, 29, 10, 582291)
            ),
        ),
    ]
