# Generated by Django 5.1.5 on 2025-06-01 05:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime(2025, 6, 1, 11, 26, 14, 127873))),
                ('video', models.FileField(upload_to='video/%y')),
                ('tumbnail', models.ImageField(upload_to='upload_profile/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
