# Generated by Django 5.1.5 on 2025-06-03 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_videos_views_alter_videos_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 21, 28, 20, 957857)),
        ),
    ]
