# Generated by Django 5.1.5 on 2025-06-07 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_profile_created_at_alter_videos_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 17, 48, 4, 471486)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 17, 48, 4, 472485)),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='watched_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
