# Generated by Django 5.1.5 on 2025-06-03 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_videos_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='videos',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 12, 35, 30, 753799)),
        ),
    ]
