# Generated by Django 5.1.5 on 2025-06-03 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_videos_caption_alter_videos_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videos',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 20, 58, 41, 931736)),
        ),
    ]
