# Generated by Django 5.1.5 on 2025-06-03 16:09

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_videos_uploaded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videos',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 3, 21, 39, 6, 768401)),
        ),
    ]
