# Generated by Django 5.1.5 on 2025-06-06 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_profile_created_at_alter_videos_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 6, 16, 43, 46, 677036)),
        ),
        migrations.AlterField(
            model_name='videos',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 6, 16, 43, 46, 680034)),
        ),
    ]
